#
# GNUmakefile
#

include $(GNUSTEP_MAKEFILES)/common.make
GNUSTEP_INSTALLATION_DIR = $(GNUSTEP_SYSTEM_ROOT)


#
# Subprojects
#
SUBPROJECTS = \
        AggregateProject   \
        ApplicationProject \
        BundleProject      \
        LibraryProject     \
        RenaissanceProject \
        ToolProject        

include $(GNUSTEP_MAKEFILES)/aggregate.make

