#
# GNUmakefile
#
# Here are the several types of modules (bundles):
#
# Project types:
#	- Aggregate
#	- Application
#	- Bundle
#	- Framework
#	- Library
#	- ResourceSet
#	- Tool
# Editors:
#	- ProjectCenter -- default PC editor
# Parsers:
#	- ObjectiveC -- that's it!
#

include $(GNUSTEP_MAKEFILES)/common.make
GNUSTEP_INSTALLATION_DIR = $(GNUSTEP_SYSTEM_ROOT)


#
# Subprojects
#
SUBPROJECTS = \
        Projects/Aggregate   	\
        Projects/Application 	\
        Projects/Bundle      	\
	Projects/Framework   	\
        Projects/Library     	\
	Projects/ResourceSet 	\
        Projects/Tool        	\
	Editors/ProjectCenter	\
	Parsers/ProjectCenter

include $(GNUSTEP_MAKEFILES)/aggregate.make

