git add Framework/PCFileManager.m
git add Framework/PCNewProjectFromSourcesPanel.m
git add Framework/PCProjectManager.m
git add Headers/ProjectCenter/PCDefines.h
git add Headers/ProjectCenter/PCFileManager.h
git add Headers/ProjectCenter/PCNewProjectFromSourcesPanel.h
git add Headers/ProjectCenter/PCProjectManager.h
git add Modules/Projects/Aggregate/PCAggregateProject.h
git add Modules/Projects/Aggregate/PCAggregateProject.m
git add Modules/Projects/Application/PCAppProject.h
git add Modules/Projects/Application/PCAppProject.m
git add Modules/Projects/Bundle/PCBundleProject.h
git add Modules/Projects/Bundle/PCBundleProject.m
git add Modules/Projects/Framework/PCFrameworkProject.h
git add Modules/Projects/Framework/PCFrameworkProject.m
git add Modules/Projects/Library/PCLibProject.h
git add Modules/Projects/Library/PCLibProject.m
git add Modules/Projects/ResourceSet/PCResourceSetProject.h
git add Modules/Projects/ResourceSet/PCResourceSetProject.m
git add Modules/Projects/Tool/PCToolProject.h
git add Modules/Projects/Tool/PCToolProject.m
git add PCMenuController.m
git add start_pasteboard_server.sh
git add bulk-add.sh
git add gdb-breakpoints.txt
git add mychanges.txt
git add rebuild.sh
git add startgdb.sh
