#
# GNUmakefile - Indentation preferences
#
PACKAGE_NAME = Indentation
include $(GNUSTEP_MAKEFILES)/common.make

#
# Bundle
#
BUNDLE_NAME = Indentation
BUNDLE_EXTENSION = .preferences
Indentation_PRINCIPAL_CLASS = PCIndentationPrefs


#
# Additional libraries
#
Indentation_LIBRARIES_DEPEND_UPON +=

#
# Resource files
#
Indentation_RESOURCE_FILES= \
  Resources/IndentationPrefs.gorm \
  Resources/Info.table

#
# Header files
#
Indentation_HEADERS= \
  PCIndentationPrefs.h

#
# Class files
#
Indentation_OBJC_FILES= \
  PCIndentationPrefs.m

include ../../GNUmakefile.bundles
include $(GNUSTEP_MAKEFILES)/bundle.make

