#
# GNUmakefile - Misc preferences
#
PACKAGE_NAME = Misc
include $(GNUSTEP_MAKEFILES)/common.make

#
# Bundle
#
BUNDLE_NAME = Misc
BUNDLE_EXTENSION = .preferences
Misc_PRINCIPAL_CLASS = PCMiscPrefs


#
# Additional libraries
#
Misc_LIBRARIES_DEPEND_UPON +=

#
# Resource files
#
Misc_RESOURCE_FILES= \
  Resources/MiscPrefs.gorm \
  Resources/Info.table

#
# Header files
#
Misc_HEADERS= \
  PCMiscPrefs.h

#
# Class files
#
Misc_OBJC_FILES= \
  PCMiscPrefs.m

include ../../GNUmakefile.bundles
include $(GNUSTEP_MAKEFILES)/bundle.make

