# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: push

# A workflow run is made up of one or more jobs that can run
# sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      LIBRARY_COMBO: gnu-gnu-gnu
      CC: gcc
      
    # Steps represent a sequence of tasks that will be executed as
    # part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE,
      # so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build source
        run: ./.github/scripts/build.sh

      # Runs a single command using the runners shell
      - name: Run tests
        run: ./.github/scripts/test.sh

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
